# ==================================================
# Jekyll Configuration for CHARTED Website
# Using Minimal Mistakes Theme + Events Collection
# ==================================================

# Site settings
title: dRTP Skills
logo: /assets/images/all-logos.png
email:
description: >-
  Write an awesome description for your new site here.
  It will appear in search results and social previews.
twitter_username: username
github_username: username

# Theme + skin
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: blue-theme  

show_last_updated_at: false

# Search
search: true

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 5
paginate_path: /page:num/
timezone: # e.g., Europe/London
future: true # Include future-dated posts


# Include folders
include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


defaults:
  # Posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false

  # Pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

# ==================================================
# Archives
# ==================================================

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/